[package]
name = "advent-of-code-2016"
version = "0.1.0"
authors = ["Chris Mears <chris@cmears.id.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
